
        [Language.ES]: {
            // ========== BEGINNER (Principiante) ==========
            [Tier.BEGINNER]: {
                1: { target: "MANZANA", hintTitle: "FRUTA", hintDesc: "Fruta roja y redonda" },
                2: { target: "PERRO", hintTitle: "ANIMAL", hintDesc: "El mejor amigo del hombre" },
                3: { target: "SOL", hintTitle: "NATURALEZA", hintDesc: "Brilla en el cielo de día" },
                4: { target: "CASA", hintTitle: "EDIFICIO", hintDesc: "Donde vive la gente" },
                5: { target: "LIBRO", hintTitle: "MEDIOS", hintDesc: "Tiene páginas para leer" },
                6: { target: "COCHE", hintTitle: "TRANSPORTE", hintDesc: "Tiene cuatro ruedas" },
                7: { target: "AGUA", hintTitle: "BEBIDA", hintDesc: "Líquido claro para beber" },
                8: { target: "PAN", hintTitle: "COMIDA", hintDesc: "Se compra en la panadería" },
                9: { target: "ARBOL", hintTitle: "PLANTA", hintDesc: "Alto, verde y con hojas" },
                10: { target: "PELOTA", hintTitle: "JUGUETE", hintDesc: "Redonda y se puede lanzar" },
                11: { target: "SILLA", hintTitle: "MUEBLE", hintDesc: "Te sientas en ella" },
                12: { target: "FLOR", hintTitle: "PLANTA", hintDesc: "Colorida y huele bien" },
                13: { target: "PEZ", hintTitle: "ANIMAL", hintDesc: "Nada en el agua" },
                14: { target: "LUNA", hintTitle: "NATURALEZA", hintDesc: "Brilla por la noche" },
                15: { target: "MESA", hintTitle: "MUEBLE", hintDesc: "Comes sobre ella" },
                16: { target: "NARIZ", hintTitle: "CUERPO", hintDesc: "Hueles con ella" },
                17: { target: "MANO", hintTitle: "CUERPO", hintDesc: "Tiene cinco dedos" },
                18: { target: "FUEGO", hintTitle: "ELEMENTO", hintDesc: "Caliente y naranja" },
                19: { target: "NIEVE", hintTitle: "TIEMPO", hintDesc: "Blanca y fría en invierno" },
                20: { target: "PIEDRA", hintTitle: "NATURALEZA", hintDesc: "Dura y está en el suelo" },
            },
            [Tier.LEARNER]: {
                1: { target: "ELEFANTE", hintTitle: "ANIMAL", hintDesc: "Animal grande con trompa" },
                2: { target: "ARCOIRIS", hintTitle: "NATURALEZA", hintDesc: "Colorido después de la lluvia" },
                3: { target: "GUITARRA", hintTitle: "MUSICA", hintDesc: "Instrumento de seis cuerdas" },
                4: { target: "VENTANA", hintTitle: "EDIFICIO", hintDesc: "Transparente, deja entrar luz" },
                5: { target: "PIÑA", hintTitle: "FRUTA", hintDesc: "Fruta tropical con espinas" },
                6: { target: "MARIPOSA", hintTitle: "ANIMAL", hintDesc: "Insecto colorido con alas" },
                7: { target: "VOLCAN", hintTitle: "NATURALEZA", hintDesc: "Montaña con lava" },
                8: { target: "SELLO", hintTitle: "CORREO", hintDesc: "Se pega en el sobre" },
                9: { target: "PINGUINO", hintTitle: "ANIMAL", hintDesc: "Pájaro blanco y negro del frío" },
                10: { target: "MERMELADA", hintTitle: "COMIDA", hintDesc: "Dulce de frutas para untar" },
                11: { target: "ZEPELIN", hintTitle: "TRANSPORTE", hintDesc: "Dirigible volador" },
                12: { target: "COCODRILO", hintTitle: "ANIMAL", hintDesc: "Reptil verde con muchos dientes" },
                13: { target: "TROMPETA", hintTitle: "MUSICA", hintDesc: "Instrumento de viento metal" },
                14: { target: "BIBLIOTECA", hintTitle: "EDIFICIO", hintDesc: "Lugar con muchos libros" },
                15: { target: "CHOCOLATE", hintTitle: "DULCE", hintDesc: "Golosina marrón" },
                16: { target: "SETA", hintTitle: "PLANTA", hintDesc: "Hongo con sombrero" },
                17: { target: "COHETE", hintTitle: "TRANSPORTE", hintDesc: "Vuela al espacio" },
                18: { target: "CAMELLO", hintTitle: "ANIMAL", hintDesc: "Animal del desierto con joroba" },
                19: { target: "BRUJULA", hintTitle: "HERRAMIENTA", hintDesc: "Señala el norte" },
                20: { target: "PIRAMIDE", hintTitle: "ESTRUCTURA", hintDesc: "Edificio triangular en Egipto" },
            },
            [Tier.SKILLED]: {
                1: { target: "FOTOSINTESIS", hintTitle: "BIOLOGIA", hintDesc: "Plantas crean energía con esto" },
                2: { target: "CUARENTENA", hintTitle: "MEDICINA", hintDesc: "Aislamiento por enfermedad" },
                3: { target: "ESTALAGMITA", hintTitle: "GEOLOGIA", hintDesc: "Formación de cueva hacia arriba" },
                4: { target: "ECUADOR", hintTitle: "GEOGRAFIA", hintDesc: "Línea imaginaria media de la Tierra" },
                5: { target: "CRONOLOGIA", hintTitle: "TIEMPO", hintDesc: "Orden de eventos en el tiempo" },
                6: { target: "METAFORA", hintTitle: "LENGUAJE", hintDesc: "Comparación figurativa" },
                7: { target: "VENTILADOR", hintTitle: "TECNOLOGIA", hintDesc: "Aparato para mover aire" },
                8: { target: "TSUNAMI", hintTitle: "NATURALEZA", hintDesc: "Ola gigante" },
                9: { target: "FOSIL", hintTitle: "HISTORIA", hintDesc: "Resto petrificado" },
                10: { target: "ASTEROIDE", hintTitle: "ESPACIO", hintDesc: "Pequeño cuerpo celeste" },
                11: { target: "MICROSCOPIO", hintTitle: "CIENCIA", hintDesc: "Agranda cosas diminutas" },
                12: { target: "DEMOCRACIA", hintTitle: "POLITICA", hintDesc: "Gobierno del pueblo" },
                13: { target: "LABERINTO", hintTitle: "ESTRUCTURA", hintDesc: "Camino confuso" },
                14: { target: "SINFONIA", hintTitle: "MUSICA", hintDesc: "Gran obra orquestal" },
                15: { target: "GENERADOR", hintTitle: "TECNOLOGIA", hintDesc: "Produce electricidad" },
                16: { target: "RENACIMIENTO", hintTitle: "HISTORIA", hintDesc: "Renacer cultural" },
                17: { target: "METAMORFOSIS", hintTitle: "BIOLOGIA", hintDesc: "Transformación de un ser" },
                18: { target: "ARCHIPIELAGO", hintTitle: "GEOGRAFIA", hintDesc: "Grupo de islas" },
                19: { target: "CALIGRAFIA", hintTitle: "ARTE", hintDesc: "Arte de escribir bello" },
                20: { target: "FERMENTACION", hintTitle: "QUIMICA", hintDesc: "Proceso de transformación" },
            },
            [Tier.EXPERT]: {
                1: { target: "CUASAR", hintTitle: "ASTRONOMIA", hintDesc: "Objeto celeste muy brillante" },
                2: { target: "PALINDROMO", hintTitle: "LINGUISTICA", hintDesc: "Se lee igual al revés" },
                3: { target: "FIBONACCI", hintTitle: "MATEMATICAS", hintDesc: "Secuencia de suma de anteriores" },
                4: { target: "OXIMORON", hintTitle: "RETORICA", hintDesc: "Combinación contradictoria" },
                5: { target: "SINESTESIA", hintTitle: "PSICOLOGIA", hintDesc: "Mezcla de sentidos" },
                6: { target: "EPIFANIA", hintTitle: "FILOSOFIA", hintDesc: "Revelación súbita" },
                7: { target: "PARADIGMA", hintTitle: "CIENCIA", hintDesc: "Modelo de pensamiento" },
                8: { target: "OSMOSIS", hintTitle: "QUIMICA", hintDesc: "Intercambio por membrana" },
                9: { target: "ANACRONISMO", hintTitle: "TIEMPO", hintDesc: "Error cronológico" },
                10: { target: "PARADOJA", hintTitle: "LOGICA", hintDesc: "Contradicción aparente" },
                11: { target: "ISOTOPO", hintTitle: "QUIMICA", hintDesc: "Variante de elemento" },
                12: { target: "CATARSIS", hintTitle: "LITERATURA", hintDesc: "Purificación emocional" },
                13: { target: "JEROGLIFICO", hintTitle: "ESCRITURA", hintDesc: "Símbolo egipcio antiguo" },
                14: { target: "NEUTRINO", hintTitle: "FISICA", hintDesc: "Partícula casi sin masa" },
                15: { target: "AUTARQUIA", hintTitle: "ECONOMIA", hintDesc: "Independencia económica" },
                16: { target: "APORIA", hintTitle: "FILOSOFIA", hintDesc: "Problema sin solución" },
                17: { target: "ECLESIOLOGIA", hintTitle: "TEOLOGIA", hintDesc: "Estudio de la iglesia" },
                18: { target: "SIMBIOSIS", hintTitle: "BIOLOGIA", hintDesc: "Vida en común beneficiosa" },
                19: { target: "ENTROPIA", hintTitle: "FISICA", hintDesc: "Medida del desorden" },
                20: { target: "ALEGORIA", hintTitle: "LITERATURA", hintDesc: "Metáfora extendida" },
            },
            [Tier.MASTER]: {
                1: { target: "SCHWARZSCHILD", hintTitle: "ASTROFISICA", hintDesc: "Radio de agujero negro" },
                2: { target: "EPISTEMOLOGIA", hintTitle: "FILOSOFIA", hintDesc: "Teoría del conocimiento" },
                3: { target: "ONOMATOPEYA", hintTitle: "LINGUISTICA", hintDesc: "Palabra que imita sonido" },
                4: { target: "ETIOLOGIA", hintTitle: "MEDICINA", hintDesc: "Estudio de causas de enfermedad" },
                5: { target: "QUINTAESENCIA", hintTitle: "FILOSOFIA", hintDesc: "Lo más puro" },
                6: { target: "FENOMENOLOGIA", hintTitle: "FILOSOFIA", hintDesc: "Estudio de fenómenos" },
                7: { target: "SUPRACONDUCTIVIDAD", hintTitle: "FISICA", hintDesc: "Sin resistencia eléctrica" },
                8: { target: "QUIASMO", hintTitle: "RETORICA", hintDesc: "Cruce de estructuras" },
                9: { target: "PALIMPSESTO", hintTitle: "LITERATURA", hintDesc: "Escrito sobre texto antiguo" },
                10: { target: "HEURISTICA", hintTitle: "LOGICA", hintDesc: "Método de resolución" },
                11: { target: "TERMODINAMICA", hintTitle: "FISICA", hintDesc: "Estudio del calor y energía" },
                12: { target: "ACLIMATACION", hintTitle: "BIOLOGIA", hintDesc: "Adaptación a ambiente" },
                13: { target: "ASINTOTA", hintTitle: "MATEMATICAS", hintDesc: "Línea que se acerca sin tocar" },
                14: { target: "APOTEOSIS", hintTitle: "MITOLOGIA", hintDesc: "Deificación" },
                15: { target: "CRIPTOGRAFIA", hintTitle: "INFORMATICA", hintDesc: "Técnica de cifrado" },
                16: { target: "ANALEPSIS", hintTitle: "NARRATIVA", hintDesc: "Flashback" },
                17: { target: "CIRCUMPOLAR", hintTitle: "ASTRONOMIA", hintDesc: "Gira alrededor del polo" },
                18: { target: "DEUTERAGONISTA", hintTitle: "TEATRO", hintDesc: "Segundo personaje principal" },
                19: { target: "ONOMATOLOGIA", hintTitle: "LINGUISTICA", hintDesc: "Estudio de nombres propios" },
                20: { target: "SIZIGIA", hintTitle: "ASTRONOMIA", hintDesc: "Alineación de astros" },
            }
        },
