/*
* ============================================
* LEXIMIX - FRAGEN & ANTWORTEN VORLAGE
* ============================================
* 
* Vollständig ausgefüllte Version mit 400 originellen Levels!
* Keine Dopplungen, keine Langeweile! 🎯
*/

import { Tier, GameMode, Language } from '../types';

export interface LevelContent {
    target: string;
    hintTitle: string;
    hintDesc: string;
    timeLimit?: number;
    type?: 'math' | 'word';
}

export const LEVEL_DATA: Record<GameMode, Record<Language, Record<Tier, Record<number, LevelContent>>>> = {

    // ========================================
    // CLASSIC MODE - DEUTSCH
    // ========================================
    [GameMode.CLASSIC]: {
        [Language.DE]: {

            // ========== BEGINNER (Anfänger) ==========
            [Tier.BEGINNER]: {
                1: { target: "APFEL", hintTitle: "OBST", hintDesc: "Runde rote Frucht, die vom Baum fällt" },
                2: { target: "HUND", hintTitle: "TIER", hintDesc: "Bester Freund des Menschen" },
                3: { target: "SONNE", hintTitle: "NATUR", hintDesc: "Leuchtet am Tag am Himmel" },
                4: { target: "HAUS", hintTitle: "GEBÄUDE", hintDesc: "Wo man wohnt" },
                5: { target: "BUCH", hintTitle: "MEDIEN", hintDesc: "Hat viele Seiten zum Lesen" },
                6: { target: "AUTO", hintTitle: "VERKEHR", hintDesc: "Fährt auf vier Rädern" },
                7: { target: "WASSER", hintTitle: "GETRÄNK", hintDesc: "Klare Flüssigkeit zum Trinken" },
                8: { target: "BROT", hintTitle: "ESSEN", hintDesc: "Wird beim Bäcker gekauft" },
                9: { target: "BAUM", hintTitle: "PFLANZE", hintDesc: "Groß, grün und hat Blätter" },
                10: { target: "BALL", hintTitle: "SPIELZEUG", hintDesc: "Rund und kann geworfen werden" },
                11: { target: "STUHL", hintTitle: "MÖBEL", hintDesc: "Darauf sitzt man" },
                12: { target: "BLUME", hintTitle: "PFLANZE", hintDesc: "Bunt und duftet schön" },
                13: { target: "FISCH", hintTitle: "TIER", hintDesc: "Schwimmt im Wasser" },
                14: { target: "MOND", hintTitle: "NATUR", hintDesc: "Leuchtet nachts am Himmel" },
                15: { target: "TISCH", hintTitle: "MÖBEL", hintDesc: "Man isst darauf" },
                16: { target: "NASE", hintTitle: "KÖRPER", hintDesc: "Damit riecht man" },
                17: { target: "HAND", hintTitle: "KÖRPER", hintDesc: "Hat fünf Finger" },
                18: { target: "FEUER", hintTitle: "ELEMENT", hintDesc: "Heiß und orange-rot" },
                19: { target: "SCHNEE", hintTitle: "WETTER", hintDesc: "Weiß und kalt im Winter" },
                20: { target: "STEIN", hintTitle: "NATUR", hintDesc: "Hart und liegt am Boden" },
            },

            // ========== LEARNER (Fortgeschritten) ==========
            [Tier.LEARNER]: {
                1: { target: "ELEFANT", hintTitle: "TIER", hintDesc: "Größtes Landtier mit Rüssel" },
                2: { target: "REGENBOGEN", hintTitle: "NATUR", hintDesc: "Bunt nach dem Regen" },
                3: { target: "GITARRE", hintTitle: "MUSIK", hintDesc: "Saiteninstrument mit sechs Saiten" },
                4: { target: "FENSTER", hintTitle: "GEBÄUDE", hintDesc: "Durchsichtig, lässt Licht rein" },
                5: { target: "ANANAS", hintTitle: "OBST", hintDesc: "Tropische Frucht mit stacheliger Schale" },
                6: { target: "SCHMETTERLING", hintTitle: "TIER", hintDesc: "Buntes Insekt mit Flügeln" },
                7: { target: "VULKAN", hintTitle: "NATUR", hintDesc: "Berg mit Lava" },
                8: { target: "BRIEFMARKE", hintTitle: "POST", hintDesc: "Klebt auf dem Umschlag" },
                9: { target: "PINGUIN", hintTitle: "TIER", hintDesc: "Schwarz-weißer Vogel aus der Antarktis" },
                10: { target: "MARMELADE", hintTitle: "ESSEN", hintDesc: "Süßer Aufstrich aus Früchten" },
                11: { target: "ZEPPELIN", hintTitle: "VERKEHR", hintDesc: "Fliegendes Luftschiff" },
                12: { target: "KROKODIL", hintTitle: "TIER", hintDesc: "Grünes Reptil mit vielen Zähnen" },
                13: { target: "TROMPETE", hintTitle: "MUSIK", hintDesc: "Blechblasinstrument" },
                14: { target: "BIBLIOTHEK", hintTitle: "GEBÄUDE", hintDesc: "Ort mit vielen Büchern" },
                15: { target: "SCHOKOLADE", hintTitle: "SÜSSIGKEIT", hintDesc: "Braune süße Leckerei" },
                16: { target: "PILZ", hintTitle: "PFLANZE", hintDesc: "Wächst im Wald, oft mit Hut" },
                17: { target: "RAKETE", hintTitle: "VERKEHR", hintDesc: "Fliegt ins Weltall" },
                18: { target: "KAMEL", hintTitle: "TIER", hintDesc: "Wüstentier mit Höcker" },
                19: { target: "KOMPASS", hintTitle: "WERKZEUG", hintDesc: "Zeigt Norden an" },
                20: { target: "PYRAMIDE", hintTitle: "BAUWERK", hintDesc: "Dreieckiges Bauwerk in Ägypten" },
            },

            // ========== SKILLED (Erfahren) ==========
            [Tier.SKILLED]: {
                1: { target: "PHOTOSYNTHESE", hintTitle: "BIOLOGIE", hintDesc: "Pflanzen produzieren damit Energie" },
                2: { target: "QUARANTÄNE", hintTitle: "MEDIZIN", hintDesc: "Isolation bei Krankheit" },
                3: { target: "STALAGMIT", hintTitle: "GEOLOGIE", hintDesc: "Tropfstein vom Boden nach oben" },
                4: { target: "ÄQUATOR", hintTitle: "GEOGRAFIE", hintDesc: "Linie um die Erdmitte" },
                5: { target: "CHRONOLOGIE", hintTitle: "ZEIT", hintDesc: "Zeitliche Abfolge von Ereignissen" },
                6: { target: "METAPHER", hintTitle: "SPRACHE", hintDesc: "Bildlicher Vergleich" },
                7: { target: "VENTILATOR", hintTitle: "TECHNIK", hintDesc: "Gerät zum Luft bewegen" },
                8: { target: "TSUNAMI", hintTitle: "NATUR", hintDesc: "Riesige Meereswelle" },
                9: { target: "FOSSIL", hintTitle: "GESCHICHTE", hintDesc: "Versteinerter Überrest" },
                10: { target: "ASTEROID", hintTitle: "WELTRAUM", hintDesc: "Kleiner Himmelskörper" },
                11: { target: "MIKROSKOP", hintTitle: "WISSENSCHAFT", hintDesc: "Vergrößert winzige Dinge" },
                12: { target: "DEMOKRATIE", hintTitle: "POLITIK", hintDesc: "Herrschaft des Volkes" },
                13: { target: "LABYRINTH", hintTitle: "STRUKTUR", hintDesc: "Verwirrender Irrgarten" },
                14: { target: "SYMPHONIE", hintTitle: "MUSIK", hintDesc: "Großes Orchesterwerk" },
                15: { target: "GENERATOR", hintTitle: "TECHNIK", hintDesc: "Erzeugt elektrischen Strom" },
                16: { target: "RENAISSANCE", hintTitle: "GESCHICHTE", hintDesc: "Kulturelle Wiedergeburt" },
                17: { target: "METAMORPHOSE", hintTitle: "BIOLOGIE", hintDesc: "Verwandlung eines Lebewesens" },
                18: { target: "ARCHIPEL", hintTitle: "GEOGRAFIE", hintDesc: "Inselgruppe" },
                19: { target: "KALLIGRAFIE", hintTitle: "KUNST", hintDesc: "Kunstvolle Schönschrift" },
                20: { target: "FERMENTATION", hintTitle: "CHEMIE", hintDesc: "Gärungsprozess" },
            },

            // ========== EXPERT (Experte) ==========
            [Tier.EXPERT]: {
                1: { target: "QUASAR", hintTitle: "ASTRONOMIE", hintDesc: "Extrem leuchtkräftiges Himmelsobjekt" },
                2: { target: "PALINDROM", hintTitle: "LINGUISTIK", hintDesc: "Wort das rückwärts gleich ist" },
                3: { target: "FIBONACCI", hintTitle: "MATHEMATIK", hintDesc: "Zahlenfolge: jede Zahl ist Summe der vorherigen zwei" },
                4: { target: "OXYMORON", hintTitle: "RHETORIK", hintDesc: "Widersprüchliche Begriffskombination" },
                5: { target: "SYNÄSTHESIE", hintTitle: "PSYCHOLOGIE", hintDesc: "Vermischung der Sinneswahrnehmungen" },
                6: { target: "EPIPHANIE", hintTitle: "PHILOSOPHIE", hintDesc: "Plötzliche Erkenntnis" },
                7: { target: "PARADIGMA", hintTitle: "WISSENSCHAFT", hintDesc: "Grundlegendes Denkmuster" },
                8: { target: "OSMOSE", hintTitle: "CHEMIE", hintDesc: "Stoffaustausch durch Membran" },
                9: { target: "ANACHRONISMUS", hintTitle: "ZEITBEGRIFF", hintDesc: "Zeitlich falsches Element" },
                10: { target: "PARADOXON", hintTitle: "LOGIK", hintDesc: "Scheinbarer Widerspruch" },
                11: { target: "ISOTOP", hintTitle: "CHEMIE", hintDesc: "Element-Variante mit gleicher Protonenzahl" },
                12: { target: "KATHARSIS", hintTitle: "LITERATUR", hintDesc: "Emotionale Reinigung" },
                13: { target: "HIEROGLYPHE", hintTitle: "SCHRIFT", hintDesc: "Altägyptisches Bildzeichen" },
                14: { target: "NEUTRINO", hintTitle: "PHYSIK", hintDesc: "Fast masseloses Elementarteilchen" },
                15: { target: "AUTARKIE", hintTitle: "WIRTSCHAFT", hintDesc: "Wirtschaftliche Unabhängigkeit" },
                16: { target: "APORIE", hintTitle: "PHILOSOPHIE", hintDesc: "Unlösbares Problem" },
                17: { target: "EKKLESIOLOGIE", hintTitle: "THEOLOGIE", hintDesc: "Lehre von der Kirche" },
                18: { target: "SYMBIOSE", hintTitle: "BIOLOGIE", hintDesc: "Zusammenleben zum gegenseitigen Nutzen" },
                19: { target: "ENTROPIE", hintTitle: "PHYSIK", hintDesc: "Maß für Unordnung" },
                20: { target: "ALLEGORIE", hintTitle: "LITERATUR", hintDesc: "Erweiterte Metapher mit Bedeutungsebenen" },
            },

            // ========== MASTER (Meister) ==========
            [Tier.MASTER]: {
                1: { target: "SCHWARZSCHILD", hintTitle: "ASTROPHYSIK", hintDesc: "Radius eines schwarzen Lochs" },
                2: { target: "EPISTEMOLOGIE", hintTitle: "PHILOSOPHIE", hintDesc: "Erkenntnistheorie" },
                3: { target: "ONOMATOPOEIA", hintTitle: "LINGUISTIK", hintDesc: "Lautmalerei" },
                4: { target: "ÄTIOLOGIE", hintTitle: "MEDIZIN", hintDesc: "Lehre von den Krankheitsursachen" },
                5: { target: "QUINTESSENZ", hintTitle: "PHILOSOPHIE", hintDesc: "Das Wesentliche" },
                6: { target: "PHÄNOMENOLOGIE", hintTitle: "PHILOSOPHIE", hintDesc: "Lehre von den Erscheinungen" },
                7: { target: "SUPRALEITFÄHIGKEIT", hintTitle: "PHYSIK", hintDesc: "Widerstandsloser Stromfluss bei tiefen Temperaturen" },
                8: { target: "CHIASMUS", hintTitle: "RHETORIK", hintDesc: "Überkreuzstellung von Satzgliedern" },
                9: { target: "PALIMPSEST", hintTitle: "LITERATUR", hintDesc: "Mehrfach beschriebenes Pergament" },
                10: { target: "HEURISTIK", hintTitle: "LOGIK", hintDesc: "Problemlösungsmethode" },
                11: { target: "THERMODYNAMIK", hintTitle: "PHYSIK", hintDesc: "Lehre von Energie und Wärme" },
                12: { target: "AKKLIMATISIERUNG", hintTitle: "BIOLOGIE", hintDesc: "Anpassung an neue Umgebung" },
                13: { target: "ASYMPTOTE", hintTitle: "MATHEMATIK", hintDesc: "Annäherungslinie ohne Berührung" },
                14: { target: "APOTHEOSE", hintTitle: "MYTHOLOGIE", hintDesc: "Vergöttlichung" },
                15: { target: "KRYPTOGRAPHIE", hintTitle: "INFORMATIK", hintDesc: "Verschlüsselungstechnik" },
                16: { target: "ANALEPSE", hintTitle: "NARRATOLOGIE", hintDesc: "Rückblende in Erzählungen" },
                17: { target: "ZIRKUMPOLAR", hintTitle: "ASTRONOMIE", hintDesc: "Um den Himmelspol kreisend" },
                18: { target: "DEUTERAGONIST", hintTitle: "DRAMA", hintDesc: "Zweite Hauptfigur" },
                19: { target: "ONOMATOLOGIE", hintTitle: "LINGUISTIK", hintDesc: "Namensforschung" },
                20: { target: "SYZYGIE", hintTitle: "ASTRONOMIE", hintDesc: "Konstellation von drei Himmelskörpern" },
            },
        },

        // ========================================
        // CLASSIC MODE - ENGLISH
        // ========================================
        [Language.EN]: {

            // ========== BEGINNER ==========
            [Tier.BEGINNER]: {
                1: { target: "APPLE", hintTitle: "FRUIT", hintDesc: "Red round fruit from tree" },
                2: { target: "DOG", hintTitle: "ANIMAL", hintDesc: "Man's best friend" },
                3: { target: "SUN", hintTitle: "NATURE", hintDesc: "Shines in the sky during day" },
                4: { target: "HOUSE", hintTitle: "BUILDING", hintDesc: "Where people live" },
                5: { target: "BOOK", hintTitle: "MEDIA", hintDesc: "Has many pages to read" },
                6: { target: "CAR", hintTitle: "TRANSPORT", hintDesc: "Drives on four wheels" },
                7: { target: "WATER", hintTitle: "DRINK", hintDesc: "Clear liquid for drinking" },
                8: { target: "BREAD", hintTitle: "FOOD", hintDesc: "Bought at the bakery" },
                9: { target: "TREE", hintTitle: "PLANT", hintDesc: "Tall, green with leaves" },
                10: { target: "BALL", hintTitle: "TOY", hintDesc: "Round and can be thrown" },
                11: { target: "CHAIR", hintTitle: "FURNITURE", hintDesc: "You sit on it" },
                12: { target: "FLOWER", hintTitle: "PLANT", hintDesc: "Colorful and smells nice" },
                13: { target: "FISH", hintTitle: "ANIMAL", hintDesc: "Swims in water" },
                14: { target: "MOON", hintTitle: "NATURE", hintDesc: "Shines at night" },
                15: { target: "TABLE", hintTitle: "FURNITURE", hintDesc: "You eat on it" },
                16: { target: "NOSE", hintTitle: "BODY", hintDesc: "You smell with it" },
                17: { target: "HAND", hintTitle: "BODY", hintDesc: "Has five fingers" },
                18: { target: "FIRE", hintTitle: "ELEMENT", hintDesc: "Hot and orange-red" },
                19: { target: "SNOW", hintTitle: "WEATHER", hintDesc: "White and cold in winter" },
                20: { target: "STONE", hintTitle: "NATURE", hintDesc: "Hard and on the ground" },
            },

            // ========== LEARNER ==========
            [Tier.LEARNER]: {
                1: { target: "ELEPHANT", hintTitle: "ANIMAL", hintDesc: "Largest land animal with trunk" },
                2: { target: "RAINBOW", hintTitle: "NATURE", hintDesc: "Colorful after rain" },
                3: { target: "GUITAR", hintTitle: "MUSIC", hintDesc: "String instrument with six strings" },
                4: { target: "WINDOW", hintTitle: "BUILDING", hintDesc: "Transparent, lets light in" },
                5: { target: "PINEAPPLE", hintTitle: "FRUIT", hintDesc: "Tropical fruit with spiky skin" },
                6: { target: "BUTTERFLY", hintTitle: "ANIMAL", hintDesc: "Colorful insect with wings" },
                7: { target: "VOLCANO", hintTitle: "NATURE", hintDesc: "Mountain with lava" },
                8: { target: "STAMP", hintTitle: "POST", hintDesc: "Sticks on envelope" },
                9: { target: "PENGUIN", hintTitle: "ANIMAL", hintDesc: "Black-white bird from Antarctica" },
                10: { target: "JAM", hintTitle: "FOOD", hintDesc: "Sweet spread made from fruit" },
                11: { target: "ZEPPELIN", hintTitle: "TRANSPORT", hintDesc: "Flying airship" },
                12: { target: "CROCODILE", hintTitle: "ANIMAL", hintDesc: "Green reptile with many teeth" },
                13: { target: "TRUMPET", hintTitle: "MUSIC", hintDesc: "Brass wind instrument" },
                14: { target: "LIBRARY", hintTitle: "BUILDING", hintDesc: "Place with many books" },
                15: { target: "CHOCOLATE", hintTitle: "SWEET", hintDesc: "Brown sweet treat" },
                16: { target: "MUSHROOM", hintTitle: "PLANT", hintDesc: "Grows in forest, often with cap" },
                17: { target: "ROCKET", hintTitle: "TRANSPORT", hintDesc: "Flies to outer space" },
                18: { target: "CAMEL", hintTitle: "ANIMAL", hintDesc: "Desert animal with hump" },
                19: { target: "COMPASS", hintTitle: "TOOL", hintDesc: "Shows north" },
                20: { target: "PYRAMID", hintTitle: "STRUCTURE", hintDesc: "Triangular building in Egypt" },
            },

            // ========== SKILLED ==========
            [Tier.SKILLED]: {
                1: { target: "PHOTOSYNTHESIS", hintTitle: "BIOLOGY", hintDesc: "Plants produce energy with this" },
                2: { target: "QUARANTINE", hintTitle: "MEDICINE", hintDesc: "Isolation during illness" },
                3: { target: "STALAGMITE", hintTitle: "GEOLOGY", hintDesc: "Cave formation growing upward" },
                4: { target: "EQUATOR", hintTitle: "GEOGRAPHY", hintDesc: "Line around Earth's middle" },
                5: { target: "CHRONOLOGY", hintTitle: "TIME", hintDesc: "Sequence of events in time" },
                6: { target: "METAPHOR", hintTitle: "LANGUAGE", hintDesc: "Figurative comparison" },
                7: { target: "VENTILATOR", hintTitle: "TECH", hintDesc: "Device to move air" },
                8: { target: "TSUNAMI", hintTitle: "NATURE", hintDesc: "Giant sea wave" },
                9: { target: "FOSSIL", hintTitle: "HISTORY", hintDesc: "Petrified remains" },
                10: { target: "ASTEROID", hintTitle: "SPACE", hintDesc: "Small celestial body" },
                11: { target: "MICROSCOPE", hintTitle: "SCIENCE", hintDesc: "Magnifies tiny things" },
                12: { target: "DEMOCRACY", hintTitle: "POLITICS", hintDesc: "Rule by the people" },
                13: { target: "LABYRINTH", hintTitle: "STRUCTURE", hintDesc: "Confusing maze" },
                14: { target: "SYMPHONY", hintTitle: "MUSIC", hintDesc: "Large orchestral work" },
                15: { target: "GENERATOR", hintTitle: "TECH", hintDesc: "Creates electrical power" },
                16: { target: "RENAISSANCE", hintTitle: "HISTORY", hintDesc: "Cultural rebirth" },
                17: { target: "METAMORPHOSIS", hintTitle: "BIOLOGY", hintDesc: "Transformation of organism" },
                18: { target: "ARCHIPELAGO", hintTitle: "GEOGRAPHY", hintDesc: "Island group" },
                19: { target: "CALLIGRAPHY", hintTitle: "ART", hintDesc: "Artistic beautiful writing" },
                20: { target: "FERMENTATION", hintTitle: "CHEMISTRY", hintDesc: "Process of fermentation" },
            },

            // ========== EXPERT ==========
            [Tier.EXPERT]: {
                1: { target: "QUASAR", hintTitle: "ASTRONOMY", hintDesc: "Extremely bright celestial object" },
                2: { target: "PALINDROME", hintTitle: "LINGUISTICS", hintDesc: "Word that reads same backwards" },
                3: { target: "FIBONACCI", hintTitle: "MATHEMATICS", hintDesc: "Number sequence where each is sum of previous two" },
                4: { target: "OXYMORON", hintTitle: "RHETORIC", hintDesc: "Contradictory term combination" },
                5: { target: "SYNESTHESIA", hintTitle: "PSYCHOLOGY", hintDesc: "Mixing of sensory perceptions" },
                6: { target: "EPIPHANY", hintTitle: "PHILOSOPHY", hintDesc: "Sudden realization" },
                7: { target: "PARADIGM", hintTitle: "SCIENCE", hintDesc: "Fundamental thought pattern" },
                8: { target: "OSMOSIS", hintTitle: "CHEMISTRY", hintDesc: "Material exchange through membrane" },
                9: { target: "ANACHRONISM", hintTitle: "TIME", hintDesc: "Chronologically misplaced element" },
                10: { target: "PARADOX", hintTitle: "LOGIC", hintDesc: "Apparent contradiction" },
                11: { target: "ISOTOPE", hintTitle: "CHEMISTRY", hintDesc: "Element variant with same proton number" },
                12: { target: "CATHARSIS", hintTitle: "LITERATURE", hintDesc: "Emotional purification" },
                13: { target: "HIEROGLYPH", hintTitle: "WRITING", hintDesc: "Ancient Egyptian pictograph" },
                14: { target: "NEUTRINO", hintTitle: "PHYSICS", hintDesc: "Nearly massless elementary particle" },
                15: { target: "AUTARKY", hintTitle: "ECONOMICS", hintDesc: "Economic independence" },
                16: { target: "APORIA", hintTitle: "PHILOSOPHY", hintDesc: "Unsolvable problem" },
                17: { target: "ECCLESIOLOGY", hintTitle: "THEOLOGY", hintDesc: "Study of the church" },
                18: { target: "SYMBIOSIS", hintTitle: "BIOLOGY", hintDesc: "Living together for mutual benefit" },
                19: { target: "ENTROPY", hintTitle: "PHYSICS", hintDesc: "Measure of disorder" },
                20: { target: "ALLEGORY", hintTitle: "LITERATURE", hintDesc: "Extended metaphor with meaning layers" },
            },

            // ========== MASTER ==========
            [Tier.MASTER]: {
                1: { target: "SCHWARZSCHILD", hintTitle: "ASTROPHYSICS", hintDesc: "Radius of a black hole" },
                2: { target: "EPISTEMOLOGY", hintTitle: "PHILOSOPHY", hintDesc: "Theory of knowledge" },
                3: { target: "ONOMATOPOEIA", hintTitle: "LINGUISTICS", hintDesc: "Words that imitate sounds" },
                4: { target: "ETIOLOGY", hintTitle: "MEDICINE", hintDesc: "Study of disease causes" },
                5: { target: "QUINTESSENCE", hintTitle: "PHILOSOPHY", hintDesc: "The essential element" },
                6: { target: "PHENOMENOLOGY", hintTitle: "PHILOSOPHY", hintDesc: "Study of phenomena" },
                7: { target: "SUPERCONDUCTIVITY", hintTitle: "PHYSICS", hintDesc: "Zero electrical resistance at low temperatures" },
                8: { target: "CHIASMUS", hintTitle: "RHETORIC", hintDesc: "Reversal of grammatical structures" },
                9: { target: "PALIMPSEST", hintTitle: "LITERATURE", hintDesc: "Manuscript written over earlier text" },
                10: { target: "HEURISTIC", hintTitle: "LOGIC", hintDesc: "Problem-solving method" },
                11: { target: "THERMODYNAMICS", hintTitle: "PHYSICS", hintDesc: "Study of energy and heat" },
                12: { target: "ACCLIMATIZATION", hintTitle: "BIOLOGY", hintDesc: "Adaptation to new environment" },
                13: { target: "ASYMPTOTE", hintTitle: "MATHEMATICS", hintDesc: "Line approaching without touching" },
                14: { target: "APOTHEOSIS", hintTitle: "MYTHOLOGY", hintDesc: "Deification" },
                15: { target: "CRYPTOGRAPHY", hintTitle: "COMPUTING", hintDesc: "Encryption technique" },
                16: { target: "ANALEPSIS", hintTitle: "NARRATOLOGY", hintDesc: "Flashback in narratives" },
                17: { target: "CIRCUMPOLAR", hintTitle: "ASTRONOMY", hintDesc: "Circling around celestial pole" },
                18: { target: "DEUTERAGONIST", hintTitle: "DRAMA", hintDesc: "Second main character" },
                19: { target: "ONOMATOLOGY", hintTitle: "LINGUISTICS", hintDesc: "Study of names" },
                20: { target: "SYZYGY", hintTitle: "ASTRONOMY", hintDesc: "Alignment of three celestial bodies" },
            },
        },
        // ========================================
        // CLASSIC MODE - SPANISH
        // ========================================
        [Language.ES]: {
            // ========== BEGINNER (Principiante) ==========
            [Tier.BEGINNER]: {
                1: { target: "MANZANA", hintTitle: "FRUTA", hintDesc: "Fruta roja y redonda" },
                2: { target: "PERRO", hintTitle: "ANIMAL", hintDesc: "El mejor amigo del hombre" },
                3: { target: "SOL", hintTitle: "NATURALEZA", hintDesc: "Brilla en el cielo de día" },
                4: { target: "CASA", hintTitle: "EDIFICIO", hintDesc: "Donde vive la gente" },
                5: { target: "LIBRO", hintTitle: "MEDIOS", hintDesc: "Tiene páginas para leer" },
                6: { target: "COCHE", hintTitle: "TRANSPORTE", hintDesc: "Tiene cuatro ruedas" },
                7: { target: "AGUA", hintTitle: "BEBIDA", hintDesc: "Líquido claro para beber" },
                8: { target: "PAN", hintTitle: "COMIDA", hintDesc: "Se compra en la panadería" },
                9: { target: "ARBOL", hintTitle: "PLANTA", hintDesc: "Alto, verde y con hojas" },
                10: { target: "PELOTA", hintTitle: "JUGUETE", hintDesc: "Redonda y se puede lanzar" },
                11: { target: "SILLA", hintTitle: "MUEBLE", hintDesc: "Te sientas en ella" },
                12: { target: "FLOR", hintTitle: "PLANTA", hintDesc: "Colorida y huele bien" },
                13: { target: "PEZ", hintTitle: "ANIMAL", hintDesc: "Nada en el agua" },
                14: { target: "LUNA", hintTitle: "NATURALEZA", hintDesc: "Brilla por la noche" },
                15: { target: "MESA", hintTitle: "MUEBLE", hintDesc: "Comes sobre ella" },
                16: { target: "NARIZ", hintTitle: "CUERPO", hintDesc: "Hueles con ella" },
                17: { target: "MANO", hintTitle: "CUERPO", hintDesc: "Tiene cinco dedos" },
                18: { target: "FUEGO", hintTitle: "ELEMENTO", hintDesc: "Caliente y naranja" },
                19: { target: "NIEVE", hintTitle: "TIEMPO", hintDesc: "Blanca y fría en invierno" },
                20: { target: "PIEDRA", hintTitle: "NATURALEZA", hintDesc: "Dura y está en el suelo" },
            },
            [Tier.LEARNER]: {
                1: { target: "ELEFANTE", hintTitle: "ANIMAL", hintDesc: "Animal grande con trompa" },
                2: { target: "ARCOIRIS", hintTitle: "NATURALEZA", hintDesc: "Colorido después de la lluvia" },
                3: { target: "GUITARRA", hintTitle: "MUSICA", hintDesc: "Instrumento de seis cuerdas" },
                4: { target: "VENTANA", hintTitle: "EDIFICIO", hintDesc: "Transparente, deja entrar luz" },
                5: { target: "PIÑA", hintTitle: "FRUTA", hintDesc: "Fruta tropical con espinas" },
                6: { target: "MARIPOSA", hintTitle: "ANIMAL", hintDesc: "Insecto colorido con alas" },
                7: { target: "VOLCAN", hintTitle: "NATURALEZA", hintDesc: "Montaña con lava" },
                8: { target: "SELLO", hintTitle: "CORREO", hintDesc: "Se pega en el sobre" },
                9: { target: "PINGUINO", hintTitle: "ANIMAL", hintDesc: "Pájaro blanco y negro del frío" },
                10: { target: "MERMELADA", hintTitle: "COMIDA", hintDesc: "Dulce de frutas para untar" },
                11: { target: "ZEPELIN", hintTitle: "TRANSPORTE", hintDesc: "Dirigible volador" },
                12: { target: "COCODRILO", hintTitle: "ANIMAL", hintDesc: "Reptil verde con muchos dientes" },
                13: { target: "TROMPETA", hintTitle: "MUSICA", hintDesc: "Instrumento de viento metal" },
                14: { target: "BIBLIOTECA", hintTitle: "EDIFICIO", hintDesc: "Lugar con muchos libros" },
                15: { target: "CHOCOLATE", hintTitle: "DULCE", hintDesc: "Golosina marrón" },
                16: { target: "SETA", hintTitle: "PLANTA", hintDesc: "Hongo con sombrero" },
                17: { target: "COHETE", hintTitle: "TRANSPORTE", hintDesc: "Vuela al espacio" },
                18: { target: "CAMELLO", hintTitle: "ANIMAL", hintDesc: "Animal del desierto con joroba" },
                19: { target: "BRUJULA", hintTitle: "HERRAMIENTA", hintDesc: "Señala el norte" },
                20: { target: "PIRAMIDE", hintTitle: "ESTRUCTURA", hintDesc: "Edificio triangular en Egipto" },
            },
            [Tier.SKILLED]: {
                1: { target: "FOTOSINTESIS", hintTitle: "BIOLOGIA", hintDesc: "Plantas crean energía con esto" },
                2: { target: "CUARENTENA", hintTitle: "MEDICINA", hintDesc: "Aislamiento por enfermedad" },
                3: { target: "ESTALAGMITA", hintTitle: "GEOLOGIA", hintDesc: "Formación de cueva hacia arriba" },
                4: { target: "ECUADOR", hintTitle: "GEOGRAFIA", hintDesc: "Línea imaginaria media de la Tierra" },
                5: { target: "CRONOLOGIA", hintTitle: "TIEMPO", hintDesc: "Orden de eventos en el tiempo" },
                6: { target: "METAFORA", hintTitle: "LENGUAJE", hintDesc: "Comparación figurativa" },
                7: { target: "VENTILADOR", hintTitle: "TECNOLOGIA", hintDesc: "Aparato para mover aire" },
                8: { target: "TSUNAMI", hintTitle: "NATURALEZA", hintDesc: "Ola gigante" },
                9: { target: "FOSIL", hintTitle: "HISTORIA", hintDesc: "Resto petrificado" },
                10: { target: "ASTEROIDE", hintTitle: "ESPACIO", hintDesc: "Pequeño cuerpo celeste" },
                11: { target: "MICROSCOPIO", hintTitle: "CIENCIA", hintDesc: "Agranda cosas diminutas" },
                12: { target: "DEMOCRACIA", hintTitle: "POLITICA", hintDesc: "Gobierno del pueblo" },
                13: { target: "LABERINTO", hintTitle: "ESTRUCTURA", hintDesc: "Camino confuso" },
                14: { target: "SINFONIA", hintTitle: "MUSICA", hintDesc: "Gran obra orquestal" },
                15: { target: "GENERADOR", hintTitle: "TECNOLOGIA", hintDesc: "Produce electricidad" },
                16: { target: "RENACIMIENTO", hintTitle: "HISTORIA", hintDesc: "Renacer cultural" },
                17: { target: "METAMORFOSIS", hintTitle: "BIOLOGIA", hintDesc: "Transformación de un ser" },
                18: { target: "ARCHIPIELAGO", hintTitle: "GEOGRAFIA", hintDesc: "Grupo de islas" },
                19: { target: "CALIGRAFIA", hintTitle: "ARTE", hintDesc: "Arte de escribir bello" },
                20: { target: "FERMENTACION", hintTitle: "QUIMICA", hintDesc: "Proceso de transformación" },
            },
            [Tier.EXPERT]: {
                1: { target: "CUASAR", hintTitle: "ASTRONOMIA", hintDesc: "Objeto celeste muy brillante" },
                2: { target: "PALINDROMO", hintTitle: "LINGUISTICA", hintDesc: "Se lee igual al revés" },
                3: { target: "FIBONACCI", hintTitle: "MATEMATICAS", hintDesc: "Secuencia de suma de anteriores" },
                4: { target: "OXIMORON", hintTitle: "RETORICA", hintDesc: "Combinación contradictoria" },
                5: { target: "SINESTESIA", hintTitle: "PSICOLOGIA", hintDesc: "Mezcla de sentidos" },
                6: { target: "EPIFANIA", hintTitle: "FILOSOFIA", hintDesc: "Revelación súbita" },
                7: { target: "PARADIGMA", hintTitle: "CIENCIA", hintDesc: "Modelo de pensamiento" },
                8: { target: "OSMOSIS", hintTitle: "QUIMICA", hintDesc: "Intercambio por membrana" },
                9: { target: "ANACRONISMO", hintTitle: "TIEMPO", hintDesc: "Error cronológico" },
                10: { target: "PARADOJA", hintTitle: "LOGICA", hintDesc: "Contradicción aparente" },
                11: { target: "ISOTOPO", hintTitle: "QUIMICA", hintDesc: "Variante de elemento" },
                12: { target: "CATARSIS", hintTitle: "LITERATURA", hintDesc: "Purificación emocional" },
                13: { target: "JEROGLIFICO", hintTitle: "ESCRITURA", hintDesc: "Símbolo egipcio antiguo" },
                14: { target: "NEUTRINO", hintTitle: "FISICA", hintDesc: "Partícula casi sin masa" },
                15: { target: "AUTARQUIA", hintTitle: "ECONOMIA", hintDesc: "Independencia económica" },
                16: { target: "APORIA", hintTitle: "FILOSOFIA", hintDesc: "Problema sin solución" },
                17: { target: "ECLESIOLOGIA", hintTitle: "TEOLOGIA", hintDesc: "Estudio de la iglesia" },
                18: { target: "SIMBIOSIS", hintTitle: "BIOLOGIA", hintDesc: "Vida en común beneficiosa" },
                19: { target: "ENTROPIA", hintTitle: "FISICA", hintDesc: "Medida del desorden" },
                20: { target: "ALEGORIA", hintTitle: "LITERATURA", hintDesc: "Metáfora extendida" },
            },
            [Tier.MASTER]: {
                1: { target: "SCHWARZSCHILD", hintTitle: "ASTROFISICA", hintDesc: "Radio de agujero negro" },
                2: { target: "EPISTEMOLOGIA", hintTitle: "FILOSOFIA", hintDesc: "Teoría del conocimiento" },
                3: { target: "ONOMATOPEYA", hintTitle: "LINGUISTICA", hintDesc: "Palabra que imita sonido" },
                4: { target: "ETIOLOGIA", hintTitle: "MEDICINA", hintDesc: "Estudio de causas de enfermedad" },
                5: { target: "QUINTAESENCIA", hintTitle: "FILOSOFIA", hintDesc: "Lo más puro" },
                6: { target: "FENOMENOLOGIA", hintTitle: "FILOSOFIA", hintDesc: "Estudio de fenómenos" },
                7: { target: "SUPRACONDUCTIVIDAD", hintTitle: "FISICA", hintDesc: "Sin resistencia eléctrica" },
                8: { target: "QUIASMO", hintTitle: "RETORICA", hintDesc: "Cruce de estructuras" },
                9: { target: "PALIMPSESTO", hintTitle: "LITERATURA", hintDesc: "Escrito sobre texto antiguo" },
                10: { target: "HEURISTICA", hintTitle: "LOGICA", hintDesc: "Método de resolución" },
                11: { target: "TERMODINAMICA", hintTitle: "FISICA", hintDesc: "Estudio del calor y energía" },
                12: { target: "ACLIMATACION", hintTitle: "BIOLOGIA", hintDesc: "Adaptación a ambiente" },
                13: { target: "ASINTOTA", hintTitle: "MATEMATICAS", hintDesc: "Línea que se acerca sin tocar" },
                14: { target: "APOTEOSIS", hintTitle: "MITOLOGIA", hintDesc: "Deificación" },
                15: { target: "CRIPTOGRAFIA", hintTitle: "INFORMATICA", hintDesc: "Técnica de cifrado" },
                16: { target: "ANALEPSIS", hintTitle: "NARRATIVA", hintDesc: "Flashback" },
                17: { target: "CIRCUMPOLAR", hintTitle: "ASTRONOMIA", hintDesc: "Gira alrededor del polo" },
                18: { target: "DEUTERAGONISTA", hintTitle: "TEATRO", hintDesc: "Segundo personaje principal" },
                19: { target: "ONOMATOLOGIA", hintTitle: "LINGUISTICA", hintDesc: "Estudio de nombres propios" },
                20: { target: "SIZIGIA", hintTitle: "ASTRONOMIA", hintDesc: "Alineación de astros" },
            }
        },
    },
    // ========================================
    // CHALLENGE MODE - DEUTSCH
    // ========================================
    [GameMode.CHALLENGE]: {
        [Language.DE]: {

            // ========== BEGINNER (Anfänger) ==========
            [Tier.BEGINNER]: {
                1: { target: "5", hintTitle: "MATHE", hintDesc: "2 + 3", type: 'math' },
                2: { target: "10", hintTitle: "MATHE", hintDesc: "5 × 2", type: 'math' },
                3: { target: "EIS", hintTitle: "RÄTSEL", hintDesc: "Gefrorenes Wasser", type: 'word' },
                4: { target: "8", hintTitle: "MATHE", hintDesc: "16 ÷ 2", type: 'math' },
                5: { target: "LICHT", hintTitle: "RÄTSEL", hintDesc: "Gegenteil von Dunkelheit", type: 'word' },
                6: { target: "12", hintTitle: "MATHE", hintDesc: "6 + 6", type: 'math' },
                7: { target: "REGEN", hintTitle: "RÄTSEL", hintDesc: "Fällt vom Himmel wenn es nass wird", type: 'word' },
                8: { target: "15", hintTitle: "MATHE", hintDesc: "3 × 5", type: 'math' },
                9: { target: "ECHO", hintTitle: "RÄTSEL", hintDesc: "Kommt zurück wenn man ruft", type: 'word' },
                10: { target: "20", hintTitle: "MATHE", hintDesc: "10 + 10", type: 'math' },
                11: { target: "SCHATTEN", hintTitle: "RÄTSEL", hintDesc: "Folgt dir aber ist nicht zu greifen", type: 'word' },
                12: { target: "6", hintTitle: "MATHE", hintDesc: "3 + 3", type: 'math' },
                13: { target: "SPIEGEL", hintTitle: "RÄTSEL", hintDesc: "Zeigt dich aber ist nicht du", type: 'word' },
                14: { target: "9", hintTitle: "MATHE", hintDesc: "18 ÷ 2", type: 'math' },
                15: { target: "KERZE", hintTitle: "RÄTSEL", hintDesc: "Je mehr sie brennt, desto kleiner wird sie", type: 'word' },
                16: { target: "14", hintTitle: "MATHE", hintDesc: "7 × 2", type: 'math' },
                17: { target: "WOLKE", hintTitle: "RÄTSEL", hintDesc: "Schwebt am Himmel, ist weiß oder grau", type: 'word' },
                18: { target: "18", hintTitle: "MATHE", hintDesc: "9 + 9", type: 'math' },
                19: { target: "TRÄNE", hintTitle: "RÄTSEL", hintDesc: "Kommt aus dem Auge wenn man weint", type: 'word' },
                20: { target: "25", hintTitle: "MATHE", hintDesc: "5 × 5", type: 'math' },
            },

            // ========== LEARNER (Fortgeschritten) ==========
            [Tier.LEARNER]: {
                1: { target: "42", hintTitle: "MATHE", hintDesc: "6 × 7", type: 'math' },
                2: { target: "36", hintTitle: "MATHE", hintDesc: "6²", type: 'math' },
                3: { target: "SCHWEIGEN", hintTitle: "RÄTSEL", hintDesc: "Man hört es, aber es macht keinen Ton", type: 'word' },
                4: { target: "50", hintTitle: "MATHE", hintDesc: "100 ÷ 2", type: 'math' },
                5: { target: "GEHEIMNIS", hintTitle: "RÄTSEL", hintDesc: "Wird leichter wenn man es teilt", type: 'word' },
                6: { target: "64", hintTitle: "MATHE", hintDesc: "8 × 8", type: 'math' },
                7: { target: "ZUKUNFT", hintTitle: "RÄTSEL", hintDesc: "Kommt immer aber ist nie da", type: 'word' },
                8: { target: "27", hintTitle: "MATHE", hintDesc: "3³", type: 'math' },
                9: { target: "HUNGER", hintTitle: "RÄTSEL", hintDesc: "Je mehr man isst, desto weniger wird es", type: 'word' },
                10: { target: "100", hintTitle: "MATHE", hintDesc: "10²", type: 'math' },
                11: { target: "VERSPRECHEN", hintTitle: "RÄTSEL", hintDesc: "Leicht zu brechen, schwer zu halten", type: 'word' },
                12: { target: "81", hintTitle: "MATHE", hintDesc: "9²", type: 'math' },
                13: { target: "HORIZONT", hintTitle: "RÄTSEL", hintDesc: "Je näher du kommst, desto weiter entfernt", type: 'word' },
                14: { target: "49", hintTitle: "MATHE", hintDesc: "7²", type: 'math' },
                15: { target: "FLAMME", hintTitle: "RÄTSEL", hintDesc: "Lebt ohne Körper, trinkt ohne Mund", type: 'word' },
                16: { target: "144", hintTitle: "MATHE", hintDesc: "12²", type: 'math' },
                17: { target: "GEDANKE", hintTitle: "RÄTSEL", hintDesc: "Schneller als Licht aber unsichtbar", type: 'word' },
                18: { target: "72", hintTitle: "MATHE", hintDesc: "8 × 9", type: 'math' },
                19: { target: "MORGEN", hintTitle: "RÄTSEL", hintDesc: "Kommt nie, aber jeder wartet darauf", type: 'word' },
                20: { target: "125", hintTitle: "MATHE", hintDesc: "5³", type: 'math' },
            },

            // ========== SKILLED (Erfahren) ==========
            [Tier.SKILLED]: {
                1: { target: "169", hintTitle: "MATHE", hintDesc: "13²", type: 'math' },
                2: { target: "196", hintTitle: "MATHE", hintDesc: "14²", type: 'math' },
                3: { target: "PARADOXON", hintTitle: "RÄTSEL", hintDesc: "Wahre Aussage die sich selbst widerspricht", type: 'word' },
                4: { target: "216", hintTitle: "MATHE", hintDesc: "6³", type: 'math' },
                5: { target: "IRONIE", hintTitle: "RÄTSEL", hintDesc: "Sagt das Gegenteil von dem was gemeint ist", type: 'word' },
                6: { target: "343", hintTitle: "MATHE", hintDesc: "7³", type: 'math' },
                7: { target: "AMBIVALENZ", hintTitle: "RÄTSEL", hintDesc: "Gleichzeitig zwei gegensätzliche Gefühle", type: 'word' },
                8: { target: "512", hintTitle: "MATHE", hintDesc: "8³", type: 'math' },
                9: { target: "DILEMMA", hintTitle: "RÄTSEL", hintDesc: "Wahl zwischen zwei schlechten Optionen", type: 'word' },
                10: { target: "225", hintTitle: "MATHE", hintDesc: "15²", type: 'math' },
                11: { target: "NOSTALGIE", hintTitle: "RÄTSEL", hintDesc: "Sehnsucht nach der Vergangenheit", type: 'word' },
                12: { target: "289", hintTitle: "MATHE", hintDesc: "17²", type: 'math' },
                13: { target: "EUPHEMISMUS", hintTitle: "RÄTSEL", hintDesc: "Beschönigende Umschreibung", type: 'word' },
                14: { target: "361", hintTitle: "MATHE", hintDesc: "19²", type: 'math' },
                15: { target: "MELANCHOLIE", hintTitle: "RÄTSEL", hintDesc: "Tiefe Schwermut ohne klaren Grund", type: 'word' },
                16: { target: "1000", hintTitle: "MATHE", hintDesc: "10³", type: 'math' },
                17: { target: "DÉJÀVU", hintTitle: "RÄTSEL", hintDesc: "Gefühl etwas schon mal erlebt zu haben", type: 'word' },
                18: { target: "729", hintTitle: "MATHE", hintDesc: "9³", type: 'math' },
                19: { target: "EUPHORIE", hintTitle: "RÄTSEL", hintDesc: "Überschwängliche Hochstimmung", type: 'word' },
                20: { target: "1728", hintTitle: "MATHE", hintDesc: "12³", type: 'math' },
            },

            // ========== EXPERT (Experte) ==========
            [Tier.EXPERT]: {
                1: { target: "2197", hintTitle: "MATHE", hintDesc: "13³", type: 'math' },
                2: { target: "2744", hintTitle: "MATHE", hintDesc: "14³", type: 'math' },
                3: { target: "APATHIE", hintTitle: "RÄTSEL", hintDesc: "Völlige Teilnahmslosigkeit", type: 'word' },
                4: { target: "3375", hintTitle: "MATHE", hintDesc: "15³", type: 'math' },
                5: { target: "ANAMNESE", hintTitle: "RÄTSEL", hintDesc: "Medizinische Vorgeschichte", type: 'word' },
                6: { target: "4096", hintTitle: "MATHE", hintDesc: "16³", type: 'math' },
                7: { target: "OBSOLESZENZ", hintTitle: "RÄTSEL", hintDesc: "Geplanter Verfall oder Veralten", type: 'word' },
                8: { target: "4913", hintTitle: "MATHE", hintDesc: "17³", type: 'math' },
                9: { target: "REKURSION", hintTitle: "RÄTSEL", hintDesc: "Definiert sich selbst durch sich selbst", type: 'word' },
                10: { target: "5832", hintTitle: "MATHE", hintDesc: "18³", type: 'math' },
                11: { target: "AMBIGUITÄT", hintTitle: "RÄTSEL", hintDesc: "Mehrdeutigkeit", type: 'word' },
                12: { target: "6859", hintTitle: "MATHE", hintDesc: "19³", type: 'math' },
                13: { target: "PLEONASMUS", hintTitle: "RÄTSEL", hintDesc: "Doppelt gemoppelt hält besser", type: 'word' },
                14: { target: "8000", hintTitle: "MATHE", hintDesc: "20³", type: 'math' },
                15: { target: "TAUTOLOGIE", hintTitle: "RÄTSEL", hintDesc: "Sagt dasselbe zweimal", type: 'word' },
                16: { target: "529", hintTitle: "MATHE", hintDesc: "23²", type: 'math' },
                17: { target: "SOPHISMUS", hintTitle: "RÄTSEL", hintDesc: "Scheinbar logische Trugschluss", type: 'word' },
                18: { target: "625", hintTitle: "MATHE", hintDesc: "25²", type: 'math' },
                19: { target: "ANTITHESE", hintTitle: "RÄTSEL", hintDesc: "Gegenbehauptung", type: 'word' },
                20: { target: "841", hintTitle: "MATHE", hintDesc: "29²", type: 'math' },
            },

            // ========== MASTER (Meister) ==========
            [Tier.MASTER]: {
                1: { target: "961", hintTitle: "MATHE", hintDesc: "31²", type: 'math' },
                2: { target: "1369", hintTitle: "MATHE", hintDesc: "37²", type: 'math' },
                3: { target: "APOPHENIE", hintTitle: "RÄTSEL", hintDesc: "Muster in zufälligen Daten erkennen", type: 'word' },
                4: { target: "1681", hintTitle: "MATHE", hintDesc: "41²", type: 'math' },
                5: { target: "SYNEKDOCHE", hintTitle: "RÄTSEL", hintDesc: "Teil für das Ganze setzen", type: 'word' },
                6: { target: "1849", hintTitle: "MATHE", hintDesc: "43²", type: 'math' },
                7: { target: "PARONOMASIE", hintTitle: "RÄTSEL", hintDesc: "Wortspiel mit ähnlichen Klängen", type: 'word' },
                8: { target: "2209", hintTitle: "MATHE", hintDesc: "47²", type: 'math' },
                9: { target: "ANAKOLUTH", hintTitle: "RÄTSEL", hintDesc: "Grammatischer Bruch im Satz", type: 'word' },
                10: { target: "2809", hintTitle: "MATHE", hintDesc: "53²", type: 'math' },
                11: { target: "METALEPSE", hintTitle: "RÄTSEL", hintDesc: "Vertauschung zeitlicher Abfolge", type: 'word' },
                12: { target: "3481", hintTitle: "MATHE", hintDesc: "59²", type: 'math' },
                13: { target: "HENDIADYOIN", hintTitle: "RÄTSEL", hintDesc: "Einen Begriff durch zwei ausdrücken", type: 'word' },
                14: { target: "3721", hintTitle: "MATHE", hintDesc: "61²", type: 'math' },
                15: { target: "ZEUGMA", hintTitle: "RÄTSEL", hintDesc: "Ein Verb für zwei verschiedene Objekte", type: 'word' },
                16: { target: "4489", hintTitle: "MATHE", hintDesc: "67²", type: 'math' },
                17: { target: "APOSIOPESE", hintTitle: "RÄTSEL", hintDesc: "Plötzliches Abbrechen des Satzes", type: 'word' },
                18: { target: "5041", hintTitle: "MATHE", hintDesc: "71²", type: 'math' },
                19: { target: "HYPERBATON", hintTitle: "RÄTSEL", hintDesc: "Ungewöhnliche Wortstellung", type: 'word' },
                20: { target: "5329", hintTitle: "MATHE", hintDesc: "73²", type: 'math' },
            },
        },

        // ========================================
        // CHALLENGE MODE - ENGLISH
        // ========================================
        [Language.EN]: {

            // ========== BEGINNER ==========
            [Tier.BEGINNER]: {
                1: { target: "5", hintTitle: "MATH", hintDesc: "2 + 3", type: 'math' },
                2: { target: "10", hintTitle: "MATH", hintDesc: "5 × 2", type: 'math' },
                3: { target: "ICE", hintTitle: "RIDDLE", hintDesc: "Frozen water", type: 'word' },
                4: { target: "8", hintTitle: "MATH", hintDesc: "16 ÷ 2", type: 'math' },
                5: { target: "LIGHT", hintTitle: "RIDDLE", hintDesc: "Opposite of darkness", type: 'word' },
                6: { target: "12", hintTitle: "MATH", hintDesc: "6 + 6", type: 'math' },
                7: { target: "RAIN", hintTitle: "RIDDLE", hintDesc: "Falls from sky when it gets wet", type: 'word' },
                8: { target: "15", hintTitle: "MATH", hintDesc: "3 × 5", type: 'math' },
                9: { target: "ECHO", hintTitle: "RIDDLE", hintDesc: "Comes back when you shout", type: 'word' },
                10: { target: "20", hintTitle: "MATH", hintDesc: "10 + 10", type: 'math' },
                11: { target: "SHADOW", hintTitle: "RIDDLE", hintDesc: "Follows you but can't be caught", type: 'word' },
                12: { target: "6", hintTitle: "MATH", hintDesc: "3 + 3", type: 'math' },
                13: { target: "MIRROR", hintTitle: "RIDDLE", hintDesc: "Shows you but isn't you", type: 'word' },
                14: { target: "9", hintTitle: "MATH", hintDesc: "18 ÷ 2", type: 'math' },
                15: { target: "CANDLE", hintTitle: "RIDDLE", hintDesc: "The more it burns, the smaller it gets", type: 'word' },
                16: { target: "14", hintTitle: "MATH", hintDesc: "7 × 2", type: 'math' },
                17: { target: "CLOUD", hintTitle: "RIDDLE", hintDesc: "Floats in sky, white or gray", type: 'word' },
                18: { target: "18", hintTitle: "MATH", hintDesc: "9 + 9", type: 'math' },
                19: { target: "TEAR", hintTitle: "RIDDLE", hintDesc: "Comes from eye when you cry", type: 'word' },
                20: { target: "25", hintTitle: "MATH", hintDesc: "5 × 5", type: 'math' },
            },

            // ========== LEARNER ==========
            [Tier.LEARNER]: {
                1: { target: "42", hintTitle: "MATH", hintDesc: "6 × 7", type: 'math' },
                2: { target: "36", hintTitle: "MATH", hintDesc: "6²", type: 'math' },
                3: { target: "SILENCE", hintTitle: "RIDDLE", hintDesc: "You hear it but it makes no sound", type: 'word' },
                4: { target: "50", hintTitle: "MATH", hintDesc: "100 ÷ 2", type: 'math' },
                5: { target: "SECRET", hintTitle: "RIDDLE", hintDesc: "Gets lighter when you share it", type: 'word' },
                6: { target: "64", hintTitle: "MATH", hintDesc: "8 × 8", type: 'math' },
                7: { target: "FUTURE", hintTitle: "RIDDLE", hintDesc: "Always coming but never here", type: 'word' },
                8: { target: "27", hintTitle: "MATH", hintDesc: "3³", type: 'math' },
                9: { target: "HUNGER", hintTitle: "RIDDLE", hintDesc: "The more you eat, the less it gets", type: 'word' },
                10: { target: "100", hintTitle: "MATH", hintDesc: "10²", type: 'math' },
                11: { target: "PROMISE", hintTitle: "RIDDLE", hintDesc: "Easy to break, hard to keep", type: 'word' },
                12: { target: "81", hintTitle: "MATH", hintDesc: "9²", type: 'math' },
                13: { target: "HORIZON", hintTitle: "RIDDLE", hintDesc: "The closer you get, the farther away", type: 'word' },
                14: { target: "49", hintTitle: "MATH", hintDesc: "7²", type: 'math' },
                15: { target: "FLAME", hintTitle: "RIDDLE", hintDesc: "Lives without body, drinks without mouth", type: 'word' },
                16: { target: "144", hintTitle: "MATH", hintDesc: "12²", type: 'math' },
                17: { target: "THOUGHT", hintTitle: "RIDDLE", hintDesc: "Faster than light but invisible", type: 'word' },
                18: { target: "72", hintTitle: "MATH", hintDesc: "8 × 9", type: 'math' },
                19: { target: "TOMORROW", hintTitle: "RIDDLE", hintDesc: "Never comes but everyone waits for it", type: 'word' },
                20: { target: "125", hintTitle: "MATH", hintDesc: "5³", type: 'math' },
            },

            // ========== SKILLED ==========
            [Tier.SKILLED]: {
                1: { target: "169", hintTitle: "MATH", hintDesc: "13²", type: 'math' },
                2: { target: "196", hintTitle: "MATH", hintDesc: "14²", type: 'math' },
                3: { target: "PARADOX", hintTitle: "RIDDLE", hintDesc: "True statement that contradicts itself", type: 'word' },
                4: { target: "216", hintTitle: "MATH", hintDesc: "6³", type: 'math' },
                5: { target: "IRONY", hintTitle: "RIDDLE", hintDesc: "Says opposite of what is meant", type: 'word' },
                6: { target: "343", hintTitle: "MATH", hintDesc: "7³", type: 'math' },
                7: { target: "AMBIVALENCE", hintTitle: "RIDDLE", hintDesc: "Two opposite feelings at once", type: 'word' },
                8: { target: "512", hintTitle: "MATH", hintDesc: "8³", type: 'math' },
                9: { target: "DILEMMA", hintTitle: "RIDDLE", hintDesc: "Choice between two bad options", type: 'word' },
                10: { target: "225", hintTitle: "MATH", hintDesc: "15²", type: 'math' },
                11: { target: "NOSTALGIA", hintTitle: "RIDDLE", hintDesc: "Longing for the past", type: 'word' },
                12: { target: "289", hintTitle: "MATH", hintDesc: "17²", type: 'math' },
                13: { target: "EUPHEMISM", hintTitle: "RIDDLE", hintDesc: "Mild expression for harsh truth", type: 'word' },
                14: { target: "361", hintTitle: "MATH", hintDesc: "19²", type: 'math' },
                15: { target: "MELANCHOLY", hintTitle: "RIDDLE", hintDesc: "Deep sadness without clear reason", type: 'word' },
                16: { target: "1000", hintTitle: "MATH", hintDesc: "10³", type: 'math' },
                17: { target: "DEJAVU", hintTitle: "RIDDLE", hintDesc: "Feeling of having experienced before", type: 'word' },
                18: { target: "729", hintTitle: "MATH", hintDesc: "9³", type: 'math' },
                19: { target: "EUPHORIA", hintTitle: "RIDDLE", hintDesc: "Intense feeling of happiness", type: 'word' },
                20: { target: "1728", hintTitle: "MATH", hintDesc: "12³", type: 'math' },
            },

            // ========== EXPERT ==========
            [Tier.EXPERT]: {
                1: { target: "2197", hintTitle: "MATH", hintDesc: "13³", type: 'math' },
                2: { target: "2744", hintTitle: "MATH", hintDesc: "14³", type: 'math' },
                3: { target: "APATHY", hintTitle: "RIDDLE", hintDesc: "Complete lack of interest", type: 'word' },
                4: { target: "3375", hintTitle: "MATH", hintDesc: "15³", type: 'math' },
                5: { target: "ANAMNESIS", hintTitle: "RIDDLE", hintDesc: "Medical history", type: 'word' },
                6: { target: "4096", hintTitle: "MATH", hintDesc: "16³", type: 'math' },
                7: { target: "OBSOLESCENCE", hintTitle: "RIDDLE", hintDesc: "Planned decay or becoming outdated", type: 'word' },
                8: { target: "4913", hintTitle: "MATH", hintDesc: "17³", type: 'math' },
                9: { target: "RECURSION", hintTitle: "RIDDLE", hintDesc: "Defines itself through itself", type: 'word' },
                10: { target: "5832", hintTitle: "MATH", hintDesc: "18³", type: 'math' },
                11: { target: "AMBIGUITY", hintTitle: "RIDDLE", hintDesc: "Having multiple meanings", type: 'word' },
                12: { target: "6859", hintTitle: "MATH", hintDesc: "19³", type: 'math' },
                13: { target: "PLEONASM", hintTitle: "RIDDLE", hintDesc: "Redundant repetition", type: 'word' },
                14: { target: "8000", hintTitle: "MATH", hintDesc: "20³", type: 'math' },
                15: { target: "TAUTOLOGY", hintTitle: "RIDDLE", hintDesc: "Says same thing twice", type: 'word' },
                16: { target: "529", hintTitle: "MATH", hintDesc: "23²", type: 'math' },
                17: { target: "SOPHISM", hintTitle: "RIDDLE", hintDesc: "Seemingly logical fallacy", type: 'word' },
                18: { target: "625", hintTitle: "MATH", hintDesc: "25²", type: 'math' },
                19: { target: "ANTITHESIS", hintTitle: "RIDDLE", hintDesc: "Counter-statement", type: 'word' },
                20: { target: "841", hintTitle: "MATH", hintDesc: "29²", type: 'math' },
            },

            // ========== MASTER ==========
            [Tier.MASTER]: {
                1: { target: "961", hintTitle: "MATH", hintDesc: "31²", type: 'math' },
                2: { target: "1369", hintTitle: "MATH", hintDesc: "37²", type: 'math' },
                3: { target: "APOPHENIA", hintTitle: "RIDDLE", hintDesc: "Seeing patterns in random data", type: 'word' },
                4: { target: "1681", hintTitle: "MATH", hintDesc: "41²", type: 'math' },
                5: { target: "SYNECDOCHE", hintTitle: "RIDDLE", hintDesc: "Part representing the whole", type: 'word' },
                6: { target: "1849", hintTitle: "MATH", hintDesc: "43²", type: 'math' },
                7: { target: "PARONOMASIA", hintTitle: "RIDDLE", hintDesc: "Pun with similar sounds", type: 'word' },
                8: { target: "2209", hintTitle: "MATH", hintDesc: "47²", type: 'math' },
                9: { target: "ANACOLUTHON", hintTitle: "RIDDLE", hintDesc: "Grammatical break in sentence", type: 'word' },
                10: { target: "2809", hintTitle: "MATH", hintDesc: "53²", type: 'math' },
                11: { target: "METALEPSIS", hintTitle: "RIDDLE", hintDesc: "Swapping temporal sequence", type: 'word' },
                12: { target: "3481", hintTitle: "MATH", hintDesc: "59²", type: 'math' },
                13: { target: "HENDIADYS", hintTitle: "RIDDLE", hintDesc: "One concept through two words", type: 'word' },
                14: { target: "3721", hintTitle: "MATH", hintDesc: "61²", type: 'math' },
                15: { target: "ZEUGMA", hintTitle: "RIDDLE", hintDesc: "One verb for two different objects", type: 'word' },
                16: { target: "4489", hintTitle: "MATH", hintDesc: "67²", type: 'math' },
                17: { target: "APOSIOPESIS", hintTitle: "RIDDLE", hintDesc: "Sudden breaking off mid-sentence", type: 'word' },
                18: { target: "5041", hintTitle: "MATH", hintDesc: "71²", type: 'math' },
                19: { target: "HYPERBATON", hintTitle: "RIDDLE", hintDesc: "Unusual word order", type: 'word' },
                20: { target: "5329", hintTitle: "MATH", hintDesc: "73²", type: 'math' },
            },
        },
    },

};
